### ISSUE TITLE
Spirit-forge-1.18.2-1.2.1      Using a soul crystal on a cage when in survival just voids the crystal

### ISSUE THREAD

**Issue by ProvoGo** [Toadstool-Studios/Spirit#1]
Title, you cant use the soul crystals in survival, the soul doesnt go into the cage

this isnt true: And if you do it in creative even with a tier 4 crystal it still doesnt spawn any mobs
tested a bit more, wasnt expecting the spawn conditions to match perfectly what it would normally be, used a tier 4 slime crystal first, but that probably only works in a slime chunk or swamp

**Comment by CodexAdrian** [comment]
Fixed in latest
