### ISSUE TITLE
Spirit 2.0.0 forge 1.18.2-40.1.52 forge startup crash

### ISSUE THREAD

**Issue by captaintekton** [Toadstool-Studios/Spirit#10]
Spirit 2.0.0 forge 1.18.2-40.1.52 forge startup crash
Here are the logs just in case they're of any use, but it looks like you've figured out the problem already.
Crash log
https://pastebin.com/AMiRgeVx
Latest log
https://pastebin.com/ksmkv0wC

**Comment by CodexAdrian** [comment]
Fixed
