### ISSUE TITLE
Bugs I found 

### ISSUE THREAD

**Issue by WitherZiby** [Toadstool-Studios/Spirit#11]
- Soul Cage, Soul Pedestal, and Crystal Pedestal can hold any item using a hopper. 
    - Items placed in Soul Pedestal via hopper are lost upon breaking. 
- Crystal Pedestals and Pedestals don't show items when using a hopper. 
- Soul Cage is visually bugged when using a hopper to take out Soul Crystal.
    - Soul Cage will still spawn the mob shown despite putting in a different soul crystal of a different mob.
    Example: Place an Evoker Soul Crystal in the Soul Cage via right-click, then place a hopper under to take out the Soul Crystal. After that, take a different Soul Crystal (Slimes for instance) and use hoppers to place soul crystal in the Soul Cage, resulting in should Evokers spawning instead of slime. 
- JEI description for Soul Cage Info on Tier Vier is missing the player distance requirement number.
- The mobs spawned from Soul Cage: 
    > Evokers spawn regular vexes
    > Slimes and Magma Cubes split into regular versions. 
- Soul Steel Bow doesn't say if it's empowered or not.

Empowered Abilities:
(Positive effects are given to target, not sure why you would want to do that but I'm hoping that's not intended)
- Blaze ability and Ghast ability has fire lasting for 120 seconds
- Dolphin ability doesn't apply dolphin grace
- Iron Golem deals 4 damage instead of 2
- Rabbit ability doesn't apply jump boost
- Ravager ability doesn't deal extra damage and extra knockback
- Turtle ability doesn't apply resistance and slowness

**Comment by WitherZiby** [comment]
Version was 2.0.0 Fabric in a single player world.

**Comment by CodexAdrian** [comment]
The potion trait is only applied to the target, yes thats intended
