### ISSUE TITLE
Wiki links are broken

### ISSUE THREAD

**Issue by Seeker14491** [Toadstool-Studios/Spirit#12]
The wiki links on [this page](https://github.com/terrarium-earth/Spirit/wiki) and the [Curse page](https://www.curseforge.com/minecraft/mc-mods/spirit) take you to a login page. The correct URL is [`https://adrian-11.gitbook.io/spirit/`](https://adrian-11.gitbook.io/spirit/).

**Comment by Seeker14491** [comment]
The link on the GitHub wiki is still broken.

**Comment by Zarvera** [comment]
Whatever it is under the link to the "wiki" is still private and inaccessible.
