### ISSUE TITLE
Crafting Fails with Cold Sweat

### ISSUE THREAD

**Issue by AveryCorvus** [Toadstool-Studios/Spirit#13]
The Cold Sweat mod modifies soul fire so that it freezes, rather than burns, making it so that the in-world crafting of Spirit doesn't work.

That feature can be disabled on the Cold Sweat side of things already, though doing so breaks a very important tool for exploring the (hot) Nether.

It would be good for Spirit to have an alternate crafting method that doesn't involve in-world crafting, e.g. right-clicking on a blue fire block while holding the item.

**Comment by CodexAdrian** [comment]
I wont be changing this, mods should not be completely overriding the functionality of an existing Minecraft block
