### ISSUE TITLE
Getting crash on startup

### ISSUE THREAD

**Issue by NoShotz** [Toadstool-Studios/Spirit#15]
When I enable this mod it errors fairly early in the log, and seemingly that error causes other errors from other mods down the line which causes the game to crash.

Latest.log
https://pastebin.com/raw/VW38cwmm

This mods error
https://pastebin.com/raw/d9dXsC1y

**Comment by CodexAdrian** [comment]
I need a little more info:

Game Version
Forge Version
Spirit Version

**Comment by NoShotz** [comment]
Minecraft 1.19
Forge 41.0.45
Spirit 2.0.3
