### ISSUE TITLE
Ticking Player error

### ISSUE THREAD

**Issue by OuroborosBoy** [Toadstool-Studios/Spirit#16]
I keep getting a ticking player error with this mod installed. It seems to happen when attempting to collect souls.
[latest.log](https://github.com/terrarium-earth/Spirit/files/9014251/latest.log)

**Comment by CodexAdrian** [comment]
This looks like its an issue with clumps I believe? Please provide some more info about your modding environment. Spirit version, Minecraft version, Forge or Fabric version and other mods.
