### ISSUE TITLE
Annoying issue with Oculus

### ISSUE THREAD

**Issue by Blugori** [Toadstool-Studios/Spirit#17]
Version : 1.18.2
Hi, I ran into an issue while using Oculus and Sildur's vibrant shaders.
When the shader is enabled, the "ghost" mobs from the spawners are invisible 
I wondered if some easy fix on my side was possible :/
thanks for reading :)
![2022-07-02_01 04 06](https://user-images.githubusercontent.com/66573974/176978907-7191a377-c723-4cfb-907d-ebecb528d0b4.png)
![2022-07-02_01 03 51](https://user-images.githubusercontent.com/66573974/176978909-503ac3de-8de3-40d4-91f8-44e2f5fe96a6.png)
!

**Comment by CodexAdrian** [comment]
Mods like Oculus are known to be very incompatible with other mods that have fancy rendering, like Botania and it's mana pools which are also incompatible with Oculus' shaders. I'd recommend putting in an issue in their GitHub page, this is their issue.
