### ISSUE TITLE
Game crashes when accessing recipe in JEI

### ISSUE THREAD

**Issue by UptightCarp03** [Toadstool-Studios/Spirit#19]
I started a fabric modded server recently through GD Launcher. I can access the recipes in singleplayer just fine but when im on my server it causes my game to crash. 

A buddy of mine took a look at the crash report and said "spirit multi block recipe JEI compatibility layer is dividing by zero".

Here is the crash report incase you need it
[crash-2022-07-07_11.10.42-client.txt](https://github.com/terrarium-earth/Spirit/files/9066347/crash-2022-07-07_11.10.42-client.txt)
.

**Comment by moon-st0ne** [comment]
same but forge
https://paste.ee/p/cEgaO

**Comment by LegendaryKaneki** [comment]
Hey. 

Had the same Issue on 2.1.0 but am now updated to 2.1.2 and have no problems with crashing when looking at the items.

**Comment by CodexAdrian** [comment]
I forgot to close this, but this is fixed now
