### ISSUE TITLE
Exception when trying to join dedicated server [1.18.2 - Spirit 2.1.3 - forge edition]

### ISSUE THREAD

**Issue by karelmikie3** [Toadstool-Studios/Spirit#21]
The client throws an exception when trying to join a dedicated server and fails to connect.

I'm running forge 40.1.60 and tested in an environment with only forge and Spirit version 2.1.3.

[server debug.log](https://github.com/terrarium-earth/Spirit/files/9126632/server.debug.log)
[server latest.log](https://github.com/terrarium-earth/Spirit/files/9126633/server.latest.log)
[client debug.log](https://github.com/terrarium-earth/Spirit/files/9126634/client.debug.log)
[client latest.log](https://github.com/terrarium-earth/Spirit/files/9126635/client.latest.log)
.

**Comment by NX-HypnicJerk** [comment]
The error I observed while joining an SMP server is:
```
Internal Exception: io.netty.handler.code.DecoderException:
com.google.gson.JsonSyntaxException: Item array cannot be empty, at least one item must be defined
```

**Comment by CodexAdrian** [comment]
Thank you, that second thing is much more helpful xd. Ill work on a fix today
