### ISSUE TITLE
Mod doesn't work in Forge 41.0.99

### ISSUE THREAD

**Issue by deinozirion** [Toadstool-Studios/Spirit#22]
I'm usinng [Spirit 2.1.2 [FORGE 1.19]](https://www.curseforge.com/minecraft/mc-mods/spirit/files/3868796) and got this:

![image](https://user-images.githubusercontent.com/109394265/179425499-766fec45-91d1-4f9e-9b9c-dc0ec0975ca0.png)

**Comment by CodexAdrian** [comment]
Im going to need a little more info than that, please send a full crash report or log

**Comment by deinozirion** [comment]
Yes, of corse
Here's the log file:
[crash-2022-07-17_16.27.49-fml.txt](https://github.com/terrarium-earth/Spirit/files/9129065/crash-2022-07-17_16.27.49-fml.txt)

**Comment by CodexAdrian** [comment]
Fixed i think
