### ISSUE TITLE
Crash using REI and seeking recipe

### ISSUE THREAD

**Issue by GreenShaman** [Toadstool-Studios/Spirit#23]
https://pastebin.com/v9DMLGES

As the title states, trying to get the recipe via REI results in a crash on many of the recipes.

**Comment by tombula77** [comment]
Same as above

[https://pastebin.com/gtrvHN2T](url)

**Comment by Tall-Bird** [comment]
Same as above.
https://pastebin.com/tpBKtrKT

**Comment by imreallybadatnames** [comment]
can replicate with just REI and spirit(architectury, cloth config and fabric api are not counted as they are dependencies)
