### ISSUE TITLE
java.lang.AbstractMethodError: Method me/codexadrian/spirit/compat/rei/categories/SoulEngulfingCategory$1.method_25396()Ljava/util/List; is abstract

### ISSUE THREAD

**Issue by TheButterbrotMan** [Toadstool-Studios/Spirit#25]
https://bytebin.lucko.me/AOxoIkPXxr

**Comment by CodexAdrian** [comment]
I cant seem to replicate this on just regular spirit + rei on fabric. Maybe its another mod causing this issue?

**Comment by CodexAdrian** [comment]
Oh this is also a duplicate of #23
