### ISSUE TITLE
Empower not working on forge

### ISSUE THREAD

**Issue by Tievoo** [Toadstool-Studios/Spirit#26]
Isolated the mod both on fabric and forge only with JEI, 1.18.2 latest version of both, empower keybind doesn't activate on forge, even after changing it several times. It works on fabric.

Versions used: 
Forge: 40.1.68
Fabric: 0.14.8

**Comment by LeftChaotix** [comment]
seems to be impacting the latest 1.19.2 version as well

**Comment by Warhand** [comment]
Can confirm, version 2.1.8 for forge has an issue where none of the tools have the ability to be empowered, with the exception of the soulsteel bow, which doesn't have a keybind to become empowered and for some reason still works as it should.

**Comment by CodexAdrian** [comment]
Fixed in latest
