### ISSUE TITLE
1.19.2 Pedestal Duplication Glitch

### ISSUE THREAD

**Issue by LeftChaotix** [Toadstool-Studios/Spirit#27]
using latest forge release for 1.19.2 (spirit-forge-1.19.1-2.1.6.jar) & forge 43.0.8

Placing an item from a stack onto a pedestal will take 1 item from your hand and result in the entire stack being duplicated onto the pedestal.

video of bug:
https://youtu.be/oW4bl_n0LFk

**Comment by CodexAdrian** [comment]
Oh shit. I think i know how to fix this, thank you for pointing this out
