### ISSUE TITLE
[1.19.2] Crash on startup, caused by The One Probe Compat

### ISSUE THREAD

**Issue by NielsPilgaard** [Toadstool-Studios/Spirit#29]
- spirit-forge-1.19.1-2.1.9
- theoneprobe-1.19-6.2.1

https://gist.github.com/NielsPilgaard/e06157909c587faf7580e72c60673b81

**Comment by CodexAdrian** [comment]
I believe i might have forgotten to reimplement my TOP support. will fix soon

**Comment by CodexAdrian** [comment]
Fixed

**Comment by NielsPilgaard** [comment]
Thanks 😊
