### ISSUE TITLE
Activator Item not working on Transmutation recipes on forge

### ISSUE THREAD

**Issue by GatoLeyo** [Toadstool-Studios/Spirit#30]
The activation item does not appear and the empty hand is replaced by default (instead of the spirit soul wand as stated on the wiki)
I've initially used the same recipe shown in the wiki so it is not a json error issue (at least I think)

Forge version: 43.1.1
Mod version: 2.1.12 (latest on 8/26/2022)

**Comment by CodexAdrian** [comment]
Thats intentional, the wand has a different purpose now, which you should be able to see if you hold shift on the wand on 1.19

**Comment by GatoLeyo** [comment]
The wand thing is true but the issue with activation items remain, even if you state anything (like a golden apple as the example code) it still asks for an empty hand and the recipe doesn't need golden apples at all
