### ISSUE TITLE
No preview in REI

### ISSUE THREAD

**Issue by masmasmas66** [Toadstool-Studios/Spirit#32]
![1626256430213](https://user-images.githubusercontent.com/107183873/190879111-d77ed365-cc1b-4ef6-85cf-a2f79248682c.jpg)
Tested in a clean install
1.19.2 
Quilt 0.17.4

only the following mods
architectury-6.2.46-fabric
cloth-config-8.2.88-fabric
quilted-fabric-api-4.0.0-beta.12+0.61.0-1.19.2
RoughlyEnoughItems-9.1.537
spirit-fabric-1.19.2-2.1.12

**Comment by CodexAdrian** [comment]
Fixed in 2.2.1
