### ISSUE TITLE
[Suggestion] Option to configure mining level of soul steel tools

### ISSUE THREAD

**Issue by Nevrai** [Toadstool-Studios/Spirit#39]
I love Spirit quite a lot, but my modpack (1.18.2) has some rare ores that require Netherite tools—and Spirit’s soul steel tools, which are fairly easy to obtain, have a mining level of Netherite.

It’d be wonderful if you could add a config option to configure the mining level of soul steel pickaxes and axes (but mainly pickaxes), so that pack makers can change it to diamond. I hope this is something that you could consider adding.

**Comment by CodexAdrian** [comment]
Hm. Well a pack maker can always just adjust the recipe of the soul steel tools or of soul steel itself. I'm not sure if I'd even be able to do that, configs might not exist by the time the game tries to register the tools. If that becomes the case ill close this issue, but if not ill do something to adjust the balance of it
