### ISSUE TITLE
Crashing when recipes for engulfing are viewed with JEI and Spirit installed

### ISSUE THREAD

**Issue by antonhibl** [Toadstool-Studios/Spirit#41]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 10/30/22, 12:02 AM
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:427)
	at me.codexadrian.spirit.compat.jei.multiblock.RotatableList.getCurrent(RotatableList.java:16)
	at me.codexadrian.spirit.compat.rei.categories.SoulEngulfingCategory.draw(SoulEngulfingCategory.java:150)
	at me.codexadrian.spirit.compat.rei.categories.SoulEngulfingCategory$1.render(SoulEngulfingCategory.java:89)
	at me.shedaniel.rei.impl.client.gui.widget.MergedWidget.render(MergedWidget.java:51)
	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.render(DelegateWidget.java:48)
	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.render(DelegateWidget.java:48)
	at me.shedaniel.rei.impl.client.gui.widget.DelegateWidgetWithTranslate.render(DelegateWidgetWithTranslate.java:58)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.render(DefaultDisplayViewingScreen.java:387)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:881)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1143)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at me.codexadrian.spirit.compat.jei.multiblock.RotatableList.getCurrent(RotatableList.java:16)
	at me.codexadrian.spirit.compat.rei.categories.SoulEngulfingCategory.draw(SoulEngulfingCategory.java:150)
	at me.codexadrian.spirit.compat.rei.categories.SoulEngulfingCategory$1.method_25394(SoulEngulfingCategory.java:89)
	at me.shedaniel.rei.impl.client.gui.widget.MergedWidget.method_25394(MergedWidget.java:51)
	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.method_25394(DelegateWidget.java:48)
	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.method_25394(DelegateWidget.java:48)
	at me.shedaniel.rei.impl.client.gui.widget.DelegateWidgetWithTranslate.method_25394(DelegateWidgetWithTranslate.java:58)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25394(DefaultDisplayViewingScreen.java:387)

-- Screen render details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen
	Mouse location: Scaled: (378, 82). Absolute: (756.582031, 164.003906)
	Screen size: Scaled: (720, 450). Absolute: (1440, 900). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['kushcola'/58, l='ClientLevel', x=-469.82, y=64.00, z=59.97]]
	Chunk stats: 1024, 473
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,74,16), Section: (at 0,10,0 in 1,4,1; chunk contains blocks 16,-64,16 to 31,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 7368140 game time, 7566988 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, illuminations/lowerres, minecraft/supporteatinganimation, VanillaTweaks_r664554, Fabric Mods, immersive-soundscapes-resources-v2.4, illuminations/pixelaccurate, continuity/default, continuity/glass_pane_culling_fix, immersive_weathering/better_brick_items, immersive_weathering/better_brick_blocks, Enhanced+Endermans, Creeper_Overhaul_RP_1.1.2, Throwable Torches Resourcepack, Vanilla-labPBR-1-3-0, cullleaves/smartleaves, immersive_weathering/biome_tinted_mossy_blocks, immersive_weathering/visual_waxed_iron_items, lambdabettergrass/default, __MoreMcmeta Internal__

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Mac OS X (aarch64) version 12.6
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 621223384 bytes (592 MiB) / 1577058304 bytes (1504 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 18432.00
	Virtual memory used (MB): 11385.92
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 703.75
	JVM Flags: 7 total; -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.5
		amecs: Amecs 1.3.8+mc.1.19-rc2
			amecsapi: Amecs API 1.3.6+mc22w17a
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19
		animatica: Animatica 0.5+1.19
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.10.33
		auditory: Auditory 0.0.3-1.19.x
		bclib: BCLib 2.0.16
		beaconoverhaul: Beacon Overhaul 1.7.1+1.19
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		bedbenefits: BedBenefits 7.1.3
		betterf3: BetterF3 1.3.2
		betterfpsdist: Better FPS distance Mod 1.19-1.9
		betterthanmending: BetterThanMending 1.3.0
		blast: BLAST 1.10
		blur: Blur (Fabric) 2.6.0
			midnightlib: MidnightLib 0.5.2
			satin: Satin 1.8.0
		boatiview: Boat Item View Fabric 0.0.3
		bookshelf: Bookshelf 15.0.1
		brb: Better Recipe Book 1.6.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.8.2
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.8.2
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.8.2
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.8.2
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.8.2
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.8.2
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.8.2
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.8.2
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.8.2
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.8.2
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.8.2
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.8.2
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.8.2
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.8.2
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.8.2
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.8.2
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.8.2
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.8.2
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.8.2
			c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.8.2
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.8.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			org_threadly_threadly: threadly 7.0
		cameraoverhaul: Camera Overhaul 1.3.1-fabric-universal
		camerautils: Camera Utils 1.19-1.0.2
		cem: Custom Entity Models 0.7.1
		chime: Chime 1.3.0
		citresewn: CIT Resewn 1.1.1+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		cleancut: CleanCut 1.19-5.0-fabric
		cleardespawn: Clear Despawn 1.1.8
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		colormatic: Colormatic 3.1.2+mc.1.19
		completeconfig: CompleteConfig 2.0.0
			coat: Coat 1.0.0-beta.17+mc22w17a
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
			completeconfig-gui-coat: completeconfig-gui-coat 2.0.0
		continuity: Continuity 2.0.0+1.19
		couplings: Couplings 1.9.1+1.19
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
		cr-arrows-info: Arrows Info 1.2.1+1.19
		creeperoverhaul: Creeper Overhaul 2.0.2
		cullleaves: Cull Leaves 2.3.4
		dark-loading-screen: Dark Loading Screen 1.6.12
		dataattributes: Data Attributes 1.2.1
		deepslatecutting: Deepslate Cutting 1.5.0
			maybe-data: Maybe data 1.3.2-1.19.2
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		draggable-resource-packs: Draggable Resource Packs 3.0.1+build.9
		dynamiccrosshair: Dynamic Crosshair 3.9+1.19
		dynamiccrosshaircompat: Dynamic Crosshair Compat 1.8+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.21+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19
		earthtojavamobs: Earth2Java 1.9.2
		easymagic: Easy Magic 4.0.0
		eatinganimationid: Eating Animation 1.8.1
		effective: Effective 1.2.2
		enchantinginfuser: Enchanting Infuser 4.0.3
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		extended_armor_bars: Extended Armor Bars 1.2.1
		extrasounds: ExtraSounds 2.3.1+1.19
			soundcategories: Sound Categories 1.2.4+1.19
		fabric: Fabric API 0.58.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricenchantments: Fabric Enchantments 0.8.0
		fabricloader: Fabric Loader 0.14.9
		fabricskyboxes: FabricSkyBoxes 0.5.6
		fallingleaves: Falling Leaves 1.12.2+1.19.2
		fallingtree: FallingTree 3.7.4
		ferritecore: FerriteCore 4.2.1
		flesh2leather: Flesh2Leather 1.0.3+1.19
		flytre_lib: FlytreLib 1.8.8
		forgeconfigapiport: Forge Config API Port 4.0.0
		freecam: Freecam 1.1.6
		friendsandfoes: Friends&Foes 1.5.5
		fwaystones: Fabric Waystones 3.0.2+mc1.19
		geckolib3: Geckolib 3.1.6
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.5.1
		gildedarmor: Gilded Armor 1.5.0+fabric-1.19
		healthoverlay: Health Overlay 7.1.1
		herdspanic: Herds Panic 1.0.6
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.5
		immersive_weathering: Immersive Weathering 1.0.1-1.19_SNAPSHOT
		incantationem: Incantationem 1.1.4+1.19
		indium: Indium 1.0.6+mc1.19
		infusion_table: Infusion Table 1.1.0
		interactic: Interactic 0.1.10+1.19
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		inventorytabs: Inventory Tabs 0.8.1-1.19.x
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		itemscroller: Item Scroller 0.16.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.1.1.239
		keybindsgalore: Keybinds Galore 1.0+1.19
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.3
		letmedespawn: Let Me Despawn fabric-1.0.2
		libraryferret: Library Ferret 2.0.0
		lithium: Lithium 0.8.1
		lottweaks: LotTweaks 2.3.4
		make_bubbles_pop: Make Bubbles Pop Mod 0.0.2-1.19
		malilib: MaLiLib 0.12.1
		mambience: MAmbience 5.2.0+1.19
		mbp: More Block Predicates 1.4
		memoryleakfix: memory Leak Fix 1.19-0.7.0
		merenc: Merge Enchantments 1.9
		minecraft: Minecraft 1.19
		mobs_attempt_parkour: Mobs Attempt Parkour 0.3-1.19-pre1
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
		modmenu: Mod Menu 4.0.0
		more_babies: More Babies 0.5.3
		moremcmeta: MoreMcmeta 1.19-3.0.5
		morevillagers: More Villagers 4.0.1
		mousetweaks: Mouse Tweaks 2.22
		naturalist: Naturalist 2.1.1
		nears: Nears 1.2.3
		noenchantcap: No Enchant Cap 2.1.2+1.19
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		onsoulfire: On Soul Fire 1.19-1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
		owo: oωo 0.7.3+1.19
		oxidized: Oxidized 1.7.1
		particlerain: Particle Rain 2.0.0
		patchouli: Patchouli 1.19-74-FABRIC
			fiber: fiber 0.23.0-2
		pigpen: PigPen 9.1.3
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		puzzleslib: Puzzles Lib 4.0.18
		quartzelv: Quartz Elevator 2.1.5+1.19
		raisedclouds: Raised Clouds 1.2.0
		rangers_haven: Ranger's Haven 2.3.3
		realisticfirespread: Realistic Fire Spread 1.19-1
		reeses-sodium-options: Reese's Sodium Options 1.4.4+mc1.19-build.47
		roughlyenoughitems: Roughly Enough Items 9.1.550
			error_notifier: Error Notifier 1.0.9
		seasons: Fabric Seasons 1.4-BETA+1.19
		shulkerboxtooltip: Shulker Box Tooltip 3.0.10+1.19
			mm: Manningham Mills 2.3
		sihywtcamd: sihywtcamd 1.7.1+1.19
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothswapping: Smooth Swapping 0.4.5
			cloth-config: Cloth Config v6 7.0.72
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.6+mc1.19-build.47
			caffeineconfig: CaffeineConfig 1.0.0+1.17
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.10
		spark: spark 1.9.26
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		spirit: Spirit 2.1.6
		stacker: Stacker 3.0.2-1.19.x
			stacc: Stacc 1.3.4
		starlight: Starlight 1.1.1+fabric.ae22326
		terralith: Terralith 2.3
		toolstats: ToolStats 11.0.2
		transparent: Transparent 5.1.0
		trinkets: Trinkets 3.4.0
		tumbleweed: Tumbleweed 0.5.1
		universalbonemeal: Universal Bone Meal 4.0.1
		visuality: Visuality 0.5.0
		weaponmaster: YDM's Weapon Master 1-19
		xaeroworldmap: Xaero's World Map 1.25.1
		ydms_redpanda: YDM's Red Panda 1.0.0
		yigd: You're in Grave Danger 1.4.1
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.9-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Apple M1 GL version 4.1 Metal - 76.3, Apple
	Window size: 1440x900
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fast
	Resource Packs: vanilla, illuminations/lowerres, minecraft/supporteatinganimation (incompatible), file/VanillaTweaks_r664554, Fabric Mods, file/immersive-soundscapes-resources-v2.4 (incompatible), illuminations/pixelaccurate, continuity/default, continuity/glass_pane_culling_fix, immersive_weathering/better_brick_items (incompatible), immersive_weathering/better_brick_blocks (incompatible), file/Enhanced+Endermans, file/Creeper_Overhaul_RP_1.1.2 (incompatible), file/Throwable Torches Resourcepack, file/Vanilla-labPBR-1-3-0, cullleaves/smartleaves, immersive_weathering/biome_tinted_mossy_blocks (incompatible), immersive_weathering/visual_waxed_iron_items (incompatible), lambdabettergrass/default
	Current Language: English (US)
	CPU: 8x Apple M1
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Spirit (spirit), Roughly Enough Items (roughlyenoughitems)

**Comment by antonhibl** [comment]
Update this only occurs in multiplayer, singleplayer works fine

**Comment by kirchner-trevor** [comment]
I am also having this issue.

Better MC modpack v9.
Minecraft 1.19.2.

[crash-2022-10-29_13.52.19-client.txt](https://github.com/terrarium-earth/Spirit/files/9896091/crash-2022-10-29_13.52.19-client.txt)

**Comment by antonhibl** [comment]
seems to be a bug related to JEI and mods that change the soul_fire_base_blocks tag. I have tried to update spirit and JEI to their newest versions and still am getting the issue. Spirit version is 2.18 and JEI is 11.1.1.239 which is the most updated version compatible with 1.19 which is what I play on.

**Comment by DoublePouce** [comment]
Exact same issue, Better MC modpack v9 on Minecraft 1.19.2.

**Comment by antonhibl** [comment]
I know the author thought this was fixed but I have updated both Spirit and JEI to the newest versions and am still seeing this bug even with only JEI and Spirit installed locally and on my server. This is still an issue, even with completely updated mods and a 1.19.2 fabric client.

**Comment by Tmyersvzn** [comment]
i'm also having this same issue, i've tried different recipe viewing mods and the only one that shows the "recipes" just crashes :(

**Comment by DirtyNative** [comment]
I am also experiencing this bug. Does anyone know if the author is working on it?

**Comment by antonhibl** [comment]
@DirtyNative best fix is to use REI instead of JEI

**Comment by antonhibl** [comment]
@Tmyersvzn REI works for me now and stopped this bug

**Comment by DirtyNative** [comment]
Which version of both mods do you use?

**Comment by antonhibl** [comment]
@DirtyNative spirit(2.2.4), REI (9.1.595), and fabric loader 14.18 for 1.19.2
