### ISSUE TITLE
Custom non-rotationally-symmetric recipes only work when built in a specific direction.

### ISSUE THREAD

**Issue by James103** [Toadstool-Studios/Spirit#47]
Minecraft 1.19.2
Forge 43.1.52
Spirit Mod 2.2.2
Modpack: All the Mods 8 version 1.0.2
See also https://github.com/AllTheMods/ATM-8/issues/310

A modpack has defined a custom Spirit Engulfing recipe that is not rotationally symmetric (meaning that the recipe as built looks different in each cardinal direction). Due to how the mod works, the recipe only works when it is built with the Teleport Pad (from the Allthemodium mod) facing south and the Dimensional Storage Actuators (from Occultism) facing north.

To reproduce:
1. Download and install the mod pack "All the Mods 8" version 1.0.2.
2. Create a new world with cheats enabled and switch to creative mode.
3. Look at the recipe for the Dimensional Seed in JEI.
4. Build the recipe block-by-block in some direction.
5. Toss in the Soulium Seed Base from Mystical Agriculture to attempt to start the recipe.
6. In 3 out of 4 directions, the recipe will fail and the input is destroyed.
7. Rebuild the recipe block-by-block facing south.
8. Toss in the input item again.
9. Notice the recipe works.

To reproduce with less mods:
1. Create a data pack that defines a custom Spirit Engulfing recipe that is not rotationally symmetric.
2. Load that data pack and attempt to build the custom recipe block by block.
3. The recipe does not work in either 2 or 3 out of the four cardinal directions. The only direction that the recipe is guaranteed to work in is with the front facing south.

**Comment by CodexAdrian** [comment]
I have spoken to the creator of these quests in ATM 8 and have explained the limitations of my system. This is intentional, as trying to account for non symmetry would make recipe validation 4 times slower.
