### ISSUE TITLE
Soul cage will not spawn entities in creative, and mobs are invisible upon soul cage spawn.

### ISSUE THREAD

**Issue by Rofl47** [Toadstool-Studios/Spirit#51]
How to Recreate:

1.  Equip Soul Crystal.
2. Kill 64 mobs of any type.
3. Place Soul Cage.
4. Right Click with Soul Crystal,

At this point, the Soul Cage will queue up the correct animation to indicate spawning, but the soul crystal will not be removed from inventory nor will any mobs spawn even after waiting upwards of 30+ seconds. This was tested at night.

Workaround: Set @p to Survival

New issue: Mobs are invisible upon spawn, or mobs will become invisible after being spawned.

I have not tested to see if the issue is related to mods that affect rendering (i.e. Optifine, Flywheel API, Oculus, etc.). It is possible this issue is related to a conflict between those mods.

**Comment by CodexAdrian** [comment]
The soul cage works exactly the same as a spawner in terms of how the conditions work. The soul crystal is not removed from your inventory in creative no, that's standard practice for mods in creative mode. 90% of the time, the cage is tested in creative so it definitely works as intended.

As for the mobs being invisible, this is definitely a result of mods affecting rendering and is a known issue, particularly with Iris/Oculus and shaders. I know no way of fixing this issue, and the mod authors of Iris have deemed this issue unsolvable, so there's no way for me to fix it.
