### ISSUE TITLE
Empowerment enables no new effects and does not register as even being enabled.

### ISSUE THREAD

**Issue by Rofl47** [Toadstool-Studios/Spirit#52]
How To Recreate:
1. Equip Soul Crystal.
2. Kill 64 mobs (preferably, a mob that has an obvious effect such as Blaze or Creeper)
3. Equip Soul-Weapon.
4. Press Empower Button.

There is no feedback acknowledging the empowerment, and using the weapon does not provide effects.

**Comment by CodexAdrian** [comment]
Hovering over the item will tell you whether or not the item is empowered or depowered, and I cannot replicate this effect not working, it works for me.
