### ISSUE TITLE
Summoning cannot be initiated or has no documentation of new mechanics.

### ISSUE THREAD

**Issue by Rofl47** [Toadstool-Studios/Spirit#53]
How to recreate (I followed a tutorial as I was attempting to teach myself the mechanics):

1.  Place Soul Pedestal and ring of Pedestals.
2. Place a Emerald in the north position, Apple in northeast position, Lapis Lazuli in the East position, Diamond in the Southeast position, Oak Sapling in the South position, Iron Block in the Southwest position, Uncarved Pumpkin in the West position, and Cooked Steak in the Northwest position. 
3. Equip Soul Crystal.
4. Kill 64 Zombies.
5. Right click soul crystal onto the Soul Pedestal.
6. Remove Soul Crystal from primary hand.
7. Right click on soul pedestal.

There is no particle effect that plays, and there appears to be no documentation regarding a change in mechanics or even summoning for this matter. Most likely this is user error, however it is requested to update the wikipedia for information about these mechanics.

**Comment by CodexAdrian** [comment]
This recipe is not present in all versions of Spirit. if you install JEI, these summoning recipes are viewable, so you need to verify that this recipe exists in your version of Spirit. I am not able to replicate my recipes striaght up not working

**Comment by DirtyNative** [comment]
And where are the recipes viewable? I could not find anything. Also it would be good if this feature would work with REI, as there is a Bug inside JEI which lets Minecraft to crash when viewing the spirit recipes
