### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CodexAdrian** [Toadstool-Studios/Spirit#64]
### Bug Description

sdfsdf

### Version

sdfsdf

### Mod Loader Version

sdfsdf

**Comment by AlexNijjar** [comment]
it's happening to me too I keep getting exit code 1. should I remove optifine?

**Comment by Chew** [comment]
Nono you need to add more RAM, removing Optifine is exit code 2

**Comment by AlexNijjar** [comment]
oh yea you’re right. i downloaded more ram and installed rubidium for good measure and now it’s working.

also can we get 1.12.2 version 🥺

**Comment by CodexAdrian** [comment]
This is still open!? i thought i closed it
